export const GET_BOOKING_DATA = 'Bookings/GET_BOOKING_DATA';
export const SET_BOOKING_DATA = 'Bookings/SET_BOOKING_DATA';
export const GET_BOOKING_DETAIL_DATA = 'Bookings/GET_BOOKING_DETAIL_DATA';
export const SET_BOOKING_DETAIL_DATA = 'Bookings/SET_BOOKING_DETAIL_DATA';